// import './globals.css';
// import { Inter } from 'next/font/google';

// const inter = Inter({ subsets: ['latin'] });

// const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function Mfe1({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>{children}</>
  )
}
